### ISSUE TITLE
Bugs bugs bugs

### ISSUE THREAD

**Issue by halfwhole** [AY1920S1-CS2103-F09-3/main#239]
- [x] `tagsp high X` or `removesptag` where X is a non-existent study plan index -- throws StudyPlanNotFoundException
- [x] `tagsp` -- tagging priority is not undo-able
- [x] `activate 1923129381239` -- Exception in thread "JavaFX Application Thread" java.lang.NumberFormatException: For input string: "1923129381239"
- [x] `undo` after `title <new title>` -- Exception in thread "JavaFX Application Thread" seedu.address.model.VersionedModulePlanner$NoUndoableStateException: Current state pointer at start of addressBookState list, unable to undo.
- [x] `undo` after `removeplan <index>` -- Exception in thread "JavaFX Application Thread" seedu.address.model.VersionedModulePlanner$NoUndoableStateException: Current state pointer at start of addressBookState list, unable to undo.
- [x] `undo` after starting afresh with a new study plan (deleting `moduleplanner.json`) -- Exception in thread "JavaFX Application Thread" seedu.address.model.VersionedModulePlanner$NoUndoableStateException: Current state pointer at start of addressBookState list, unable to undo.
- [x] `redo` after starting afresh with a new study plan (deleting `moduleplanner.json`) -- Exception in thread "JavaFX Application Thread" seedu.address.model.VersionedModulePlanner$NoRedoableStateException: Current state pointer at end of addressBookState list, unable to redo.
- [x] `viewcommit 1.1111111111111` Exception in thread "JavaFX Application Thread" java.lang.NumberFormatException: For input string: "1111111111111"
- [x] `revert 1.1111111111111` Exception in thread "JavaFX Application Thread" java.lang.NumberFormatException: For input string: "1111111111111"
- [x] `deletecommit 1.1111111111111` Exception in thread "JavaFX Application Thread" java.lang.NumberFormatException: For input string: "1111111111111"
- [ ] adding the same module to multiple semesters
- [x] `tagmod cs1231s a b c d e f g` -- tags it with g and nothing else, is this expected?
- [x] `check` -- doesn't discriminate between user tags that end in `:P`, or core modules that are done across semesters
- [x] `addmod y1st1 cs1101s` or `addmod y5s1 cs1101s` -- system prints `ERROR HERE` and Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at seedu.address.model.ModelManager.semesterHasModule(ModelManager.java:265)
	at seedu.address.logic.commands.cli.AddModuleCommand.execute(AddModuleCommand.java:41) ...
- [x] Same as above for `removemod y5s1 cs1101s` etc.
- [x] `renamemodtag core` (without second argument) -- Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1

**Comment by yaaanch** [comment]
- `addmod y1s1 cs2030 cs2040s` will add only the last module.

**Comment by halfwhole** [comment]
- [ ] `removemod y1s1 cs2030 cs2040s` will remove only the last module too
